import React from 'react';
import divingtripsitinerary  from '../../../../assets/images/diving-trips-itinerary.jpeg';
import classes from '../Jumbotron/Jumbotron.module.css';



const Jumbotron = () => {
    return (
        <div className={classes.Jumbotron}>
{/* add hero background to stretch image over page and add overlay  */}

                
            <img className={classes.overlayprimary} src={divingtripsitinerary} alt= "Woman snorkeling" />  

                
   
                <div className="overlay-content">
                    <h4>Underwater and out of the world</h4>
                    <p>Diving in the waters of Dominica, you will feel that an unspoiled underwater world awaits you. And that's the case! Magnificent coral reef gardens will escort you to walls and pinnacles, all generated by ancient volcanic activity all around the island.</p>
                </div>
           
                    <button>FAVORITE THIS ROUTE</button> 
                      
        </div>

          
            
          

        
    );
};

export default Jumbotron;