import React from 'react';
import divingtripsitinerary  from '../../../../assets/images/diving-trips-itinerary.jpeg';
import classes from '../Jumbotron/Jumbotron.module.css';



const Jumbotron = () => {
    return (
        <div>
            
            <div className={classes.Jumbotron}>
            <img src= {divingtripsitinerary} alt= "Woman snorkeling " className={classes.backgroundImage} /> 

            <h1 className={classes.display}>Underwater and out of the world</h1>
            <p className="lead">Diving in the waters of Dominica, you will feel that an unspoiled underwater world awaits you. And that's the case! Magnificent coral reef gardens will escort you to walls and pinnacles, all generated by ancient volcanic activity all around the island.</p>
            <p className="lead">
                <button>FAVORITE THIS ROUTE</button>
            </p>
            </div>

        </div>
    );
};

export default Jumbotron;